### ISSUE TITLE
Investigate pytest issues on CI

### ISSUE THREAD

**Issue by davfsa** [hikari-py/hikari#1010]
CI run logs: [logs_5403.zip](https://github.com/hikari-py/hikari/files/8015710/logs_5403.zip)

Failing pipeline: `test (macos-latest, 3.9)`

**Comment by davfsa** [comment]
2 errors I found:

1. Warning raised by slow tests, fixed by #1005, as it rewrites the test. These should have been test errors but they were captured as thread warnings instead unfortunately, so it took some time to catch. @FasterSpeeding this is the test you told me about. Ig I fixed it by mistake 😅 
```
2022-02-07T13:17:06.0187500Z tests/hikari/impl/test_rate_limits.py::TestWindowedBurstRateLimiter::test_throttle_when_limited_sleeps_then_bursts_repeatedly
2022-02-07T13:17:06.0188250Z   /Users/runner/work/hikari/hikari/.nox/pytest/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-5
2022-02-07T13:17:06.0188630Z   
2022-02-07T13:17:06.0188810Z   Traceback (most recent call last):
2022-02-07T13:17:06.0202960Z     File "/Users/runner/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/threading.py", line 973, in _bootstrap_inner
2022-02-07T13:17:06.0203420Z       self.run()
2022-02-07T13:17:06.0203790Z     File "/Users/runner/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/threading.py", line 910, in run
2022-02-07T13:17:06.0204110Z       self._target(*self._args, **self._kwargs)
2022-02-07T13:17:06.0205110Z     File "/Users/runner/work/hikari/hikari/tests/hikari/impl/test_rate_limits.py", line 343, in _run_test_throttle_logic_on_this_thread
2022-02-07T13:17:06.0205510Z       event_loop.run_until_complete(self._run_test_throttle_logic_on_loop(event_loop))
2022-02-07T13:17:06.0205950Z     File "/Users/runner/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2022-02-07T13:17:06.0206270Z       return future.result()
2022-02-07T13:17:06.0206650Z     File "/Users/runner/work/hikari/hikari/tests/hikari/impl/test_rate_limits.py", line 396, in _run_test_throttle_logic_on_loop
2022-02-07T13:17:06.0207340Z       assert math.isclose(next_first - previous_last, period, abs_tol=max_distance_within_window), (
2022-02-07T13:17:06.0207720Z   AssertionError: distance between windows is not acceptable! 0=39.98175229 1=41.582799405, max diff = 0.05
2022-02-07T13:17:06.0207980Z   assert False
2022-02-07T13:17:06.0208390Z    +  where False = <built-in function isclose>((41.582799405 - 39.98175229), 1.5, abs_tol=0.05)
2022-02-07T13:17:06.0208780Z    +    where <built-in function isclose> = math.isclose
2022-02-07T13:17:06.0209290Z   
2022-02-07T13:17:06.0209580Z     warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
2022-02-07T13:17:06.0209800Z 
2022-02-07T13:17:06.0209970Z tests/hikari/test_channels.py::TestTextChannel::test_trigger_typing
2022-02-07T13:17:06.0210810Z   tests/hikari/test_channels.py:302: PytestWarning: The test <Function test_trigger_typing> is marked with '@pytest.mark.asyncio' but it is not an async function. Please remove asyncio marker. If the test is not marked explicitly, check for global markers applied via 'pytestmark'.
2022-02-07T13:17:06.0211330Z     def test_trigger_typing(self, model):
2022-02-07T13:17:06.0211480Z 
2022-02-07T13:17:06.0211760Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

2. Apart from the repr for `TimedCacheMap` being horrible for debugging this, it looks like another speed issue. #1005 also fixes this by completely removing the tests for it. If we were to keep it, I think there is also a way to not make it flaky
```
2022-02-07T13:17:05.9862020Z ____________ TestTimedCacheMap.test___setitem___garbage_collection _____________
2022-02-07T13:17:05.9862570Z 
2022-02-07T13:17:05.9863100Z self = <tests.hikari.internal.test_collections.TestTimedCacheMap object at 0x1066f03a0>
2022-02-07T13:17:05.9863970Z 
2022-02-07T13:17:05.9864460Z     @pytest.mark.asyncio()
2022-02-07T13:17:05.9864990Z     async def test___setitem___garbage_collection(self):
2022-02-07T13:17:05.9865520Z         mock_map = collections.TimedCacheMap(
2022-02-07T13:17:05.9866120Z             expiry=datetime.timedelta(seconds=hikari_test_helpers.REASONABLE_QUICK_RESPONSE_TIME * 3)
2022-02-07T13:17:05.9866660Z         )
2022-02-07T13:17:05.9867100Z         mock_map["OK"] = "no"
2022-02-07T13:17:05.9868290Z         await asyncio.sleep(hikari_test_helpers.REASONABLE_QUICK_RESPONSE_TIME * 2)
2022-02-07T13:17:05.9868850Z         assert mock_map == {"OK": "no"}
2022-02-07T13:17:05.9869350Z         mock_map["ayanami"] = "rei"
2022-02-07T13:17:05.9869850Z >       assert mock_map == {"OK": "no", "ayanami": "rei"}
2022-02-07T13:17:05.9870780Z E       AssertionError: assert <hikari.inter...t 0x1060cff40> == {'OK': 'no', 'ayanami': 'rei'}
2022-02-07T13:17:05.9871360Z E         Full diff:
2022-02-07T13:17:05.9871960Z E         - {'OK': 'no', 'ayanami': 'rei'}
2022-02-07T13:17:05.9872580Z E         + <hikari.internal.collections.TimedCacheMap object at 0x1060cff40>
2022-02-07T13:17:05.9873010Z 
2022-02-07T13:17:05.9873200Z mock_map   = <hikari.internal.collections.TimedCacheMap object at 0x1060cff40>
2022-02-07T13:17:05.9873600Z self       = <tests.hikari.internal.test_collections.TestTimedCacheMap object at 0x1066f03a0>
2022-02-07T13:17:05.9873820Z 
2022-02-07T13:17:05.9873960Z tests/hikari/internal/test_collections.py:251: AssertionError
2022-02-07T13:17:05.9874490Z ------------------------------ Captured log call -------------------------------
2022-02-07T13:17:05.9876750Z WARNING  asyncio:base_events.py:1885 Executing <Task pending name='Task-5' coro=<TestTimedCacheMap.test___setitem___garbage_collection() running at /Users/runner/work/hikari/hikari/tests/hikari/internal/test_collections.py:248> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x105b67c10>()] created at /Users/runner/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/base_events.py:424> cb=[_run_until_complete_cb() at /Users/runner/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/asyncio/base_events.py:184] created at /Users/runner/work/hikari/hikari/.nox/pytest/lib/python3.9/site-packages/pytest_asyncio/plugin.py:445> took 0.207 seconds
```
